# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always

  go-service:
    build:
      context: ../StreamPlatformLite-Backend
      dockerfile: ../StreamPlatformLite-Backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 1935:1935
    depends_on:
      - mongo
      - redis
    environment:
      SERVER_PORT: 8080
      MONGODB_URI: mongodb://root:example@mongo:27017
      MONGODB_DATABASE: go_service
      APP_SECRET_KEY: example_secret_key
      DISCORD_CLIENT_ID: example_client_id
      DISCORD_CLIENT_SECRET: example_client_secret
      DISCORD_ADMIN_ID: example_admin_id
      DISCORD_GUILD_ID: example_guild_id
      DOMAIN: localhost
      FRONTEND_DOMAIN: localhost
      FRONTEND_PORT: 3000
      REDIS_URI: redis:6379
      HTTPS: "false"
  frontend:
    build:
      context: ../StreamPlatformLite-Frontend
      dockerfile: ../StreamPlatformLite-Frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:8080
      - DISCORD_URL=example_discord_url
volumes:
  mongo-data: